### ISSUE TITLE
Hiresfix for flux gives me this 'NoneType' object has no attribute 'sd_checkpoint_info'

### ISSUE THREAD

**Issue by DarkViewAI** [lllyasviel/stable-diffusion-webui-forge#2136]
AttributeError: 'NoneType' object has no attribute 'sd_checkpoint_info'
Time taken: 0.0 sec.

    assert isinstance(state_dict, dict) and len(state_dict) > 16, 'You do not have CLIP state dict!'
AssertionError: You do not have CLIP state dict!
[Unload] Trying to free all memory for cuda:0 with 0 models keep loaded ... Done.
Traceback (most recent call last):
  File "D:\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui-forge\modules_forge\main_thread.py", line 30, in work
    self.result = self.func(*self.args, **self.kwargs)
  File "D:\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui-forge\modules\txt2img.py", line 125, in txt2img_function
    processed = processing.process_images(p)
  File "D:\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui-forge\modules\processing.py", line 840, in process_images
    res = process_images_inner(p)
  File "D:\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui-forge\modules\processing.py", line 877, in process_images_inner
    p.sd_model_name = shared.sd_model.sd_checkpoint_info.name_for_extra
'NoneType' object has no attribute 'sd_checkpoint_info'
AttributeError: 'NoneType' object has no attribute 'sd_checkpoint_info'
Traceback (most recent call last):
  File "D:\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui-forge\modules_forge\main_thread.py", line 30, in work
'NoneType' object has no attribute 'sd_checkpoint_info'
    self.result = self.func(*self.args, **self.kwargs)
  File "D:\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui-forge\modules\txt2img.py", line 125, in txt2img_function
    processed = processing.process_images(p)
  File "D:\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui-forge\modules\processing.py", line 840, in process_images
    res = process_images_inner(p)
  File "D:\StabilityMatrix-win-x64\Data\Packages\stable-diffusion-webui-forge\modules\processing.py", line 877, in process_images_inner
    p.sd_model_name = shared.sd_model.sd_checkpoint_info.name_for_extra
AttributeError: 'NoneType' object has no attribute 'sd_checkpoint_info'

**Comment by zappityzap** [comment]
Seems to be caused by commit [aaa2fe7](https://github.com/lllyasviel/stable-diffusion-webui-forge/commit/aaa2fe761ba5dce8b0126fe6858cd7f4ad9166ce) from #2116. The version before it works for me. @DenOfEquity

**Comment by DenOfEquity** [comment]
If the model you use for the highresfix pass requires additional modules (VAE, CLIP, T5) you need to specify them. (if the first pass model also used them, you can set 'Use same choices', not empty selection). The only way I've been able to induce a similar error is by not providing the necessary modules. I've tested, for example:
* 1.5 (built-in VAE) -> 1.5 (no built-in VAE, instead specified in *Hires VAE / Text Encoder*)
* 1.5 <-> Flux
* XL <-> Flux
* Flux (without built-in modules, instead specified in *VAE / Text Encoder*) -> Flux (without built-in modules; 'Use same choices' in *Hires VAE / Text Encoder*)
* Flux (with built-in modules) -> Flux (without built-in modules, instead specified in *Hires VAE / Text Encoder*)

**Comment by DenOfEquity** [comment]
You have exposed a bug too, so thanks for your comments.
The default for hires checkpoint and modules is to use the first pass settings, but that didn't happen in your case. I think the issue came from imprecise handling of infotext (settings taken from images or the blue arrow button), incorrectly clearing the Hires VAE / Text Encoder; so I've patched that. I also wonder if these selections should always be visible now (instead of behind an option), as Flux has made them more important.
