### ISSUE TITLE
Broken by 82dfc2b - torch has no attribute 'uint16'

### ISSUE THREAD

**Issue by altoiddealer** [lllyasviel/stable-diffusion-webui-forge#1514]
The fix is probably "Re-install Torch"

I'm going to go try that.

In the meantime, please be aware that anyone simply upgrading their Forge will only be greeted by this error here:

![Screenshot 2024-08-26 094531](https://github.com/user-attachments/assets/f79f459f-4ecd-432d-9d8d-580f0e4c324a)

I walked back each commit with `git checkout`

Here is the commit that **WORKED** (82dfc2b BROKE it)

![Screenshot 2024-08-26 095427](https://github.com/user-attachments/assets/bedf6747-c7a5-4a82-8638-ec878942e662)

![Screenshot 2024-08-26 095454](https://github.com/user-attachments/assets/7fb1a97f-b170-40cb-be1b-e4f37e26af4b)

**Comment by altoiddealer** [comment]
Wonderful timing heh...

I see this commit just appeared...

https://github.com/lllyasviel/stable-diffusion-webui-forge/commit/acf99dd74eed27222da74b96466a526c9db640c8

Trying that now...

**Comment by altoiddealer** [comment]
### Yes, good to go :)

![Screenshot 2024-08-26 100143](https://github.com/user-attachments/assets/3f698d53-fd3a-4c9a-9905-aae42e4ea466)

**Comment by altoiddealer** [comment]
Also yes I see that Torch needs upgrade
